name: taxiCarpool-github-actions

on:
  push:
    branches: [ main ]

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      SPRING_DATASOURCE_URL:      ${{ secrets.SPRING_DATASOURCE_URL }}
      SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
      EMAIL_VERIFICATION_GOOGLE_ID:      ${{ secrets.EMAIL_VERIFICATION_GOOGLE_ID }}
      EMAIL_VERIFICATION_GOOGLE_PW:      ${{ secrets.EMAIL_VERIFICATION_GOOGLE_PW }}
      EMAIL_VERIFICATION_GOOGLE_ADDRESS: ${{ secrets.EMAIL_VERIFICATION_GOOGLE_ADDRESS }}
      KAKAO_APP_REST_KEY:                ${{ secrets.KAKAO_APP_REST_KEY }}
      JWT_SECRET:                        ${{ secrets.JWT_SECRET }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Set up SSH Key
      run: |
        echo "${{ secrets.EC2_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Add EC2 Host to Known Hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Grant execute permission to Gradle wrapper
      run: chmod +x ./gradlew
      working-directory: ./taxi-carpool

    - name: Build
      run: ./gradlew clean build
      working-directory: ./taxi-carpool

    - name: Make Directories on EC2
      run: ssh -i ../key.pem ec2-user@${{ secrets.EC2_HOST }} "mkdir -p /home/ec2-user/deploys /home/ec2-user/logs"
      working-directory: ./taxi-carpool

    - name: Upload JAR to EC2
      run: scp -i ../key.pem build/libs/taxi-carpool-0.0.1-SNAPSHOT.jar ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/deploys/taxi-carpool-0.0.1-SNAPSHOT.jar
      working-directory: ./taxi-carpool
    
    - name: Start Spring App on EC2
      run: |
        ssh -i ../key.pem ec2-user@${{ secrets.EC2_HOST }} "
          pkill -f 'java' || true &&
          nohup \
            SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }} \
            SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }} \
            SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }} \
            EMAIL_VERIFICATION_GOOGLE_ID=${{ secrets.EMAIL_VERIFICATION_GOOGLE_ID }} \
            EMAIL_VERIFICATION_GOOGLE_PW=${{ secrets.EMAIL_VERIFICATION_GOOGLE_PW }} \
            EMAIL_VERIFICATION_GOOGLE_ADDRESS=${{ secrets.EMAIL_VERIFICATION_GOOGLE_ADDRESS }} \
            KAKAO_APP_REST_KEY=${{ secrets.KAKAO_APP_REST_KEY }} \
            JWT_SECRET=${{ secrets.JWT_SECRET }} \
            java -Dspring.profiles.active=prod -jar /home/ec2-user/deploys/taxi-carpool-0.0.1-SNAPSHOT.jar > /home/ec2-user/logs/log.txt 2>&1 &"

