name: taxiCarpool-github-actions

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ develop ]

jobs: 
  build-and-deploy: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'

    - name: Grant execute permission to Gradle wrapper
      run: chmod +x ./gradlew

    - name: Build
      run: ./gradlew clean build

    - name: Deploy to EC2
      run: |
        scp -i ${{ secrets.EC2_KEY }} ./build/libs/app.jar ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/app.jar
        ssh -i ${{ secrets.EC2_KEY }} ec2-user@${{ secrets.EC2_HOST }} "pkill -f 'java' || true && nohup java -jar /home/ec2-user/app.jar > log.txt 2>&1 &"
